### ISSUE TITLE
Support usage of preset for PTZ cameras

### ISSUE THREAD

**Issue by mguyard** [user2684/imouapi#13]
### Description
Hello,

Can you implement these API endpoints to manage PTZ preset :

- Retrieve favorite : https://openapi-[datacenter].easy4ip.com/openapi/getCollection
- Set Favorite : https://openapi-[datacenter].easy4ip.com/openapi/setCollection
- Modify Favorite : https://openapi-[datacenter].easy4ip.com/openapi/modifyCollection
- Delete Favorite : https://openapi-[datacenter].easy4ip.com/openapi/deleteCollection
- Move to a Favorite : https://openapi-[datacenter].easy4ip.com/openapi/turnCollection

https://github.com/user2684/imou_life/issues/75#issuecomment-2395472556

Thank you

**Comment by user2684** [comment]
Hi, have a look at [this](https://github.com/user2684/imou_life/wiki/Is-this-an-official-integration%3F), I think the functionality is already there
