### ISSUE TITLE
Turn on record on local storage

### ISSUE THREAD

**Issue by jkvint** [user2684/imouapi#5]
Hello
I can enable video recording to local storage via api? 
I didn't find how to do it in your documentation

**Comment by user2684** [comment]
Hi, I don't think so or at least I couldn't find it in the API documentation (https://open.imoulife.com/book/en/start.html). In case you will have more luck let me know and I'll implement it. Thx

**Comment by user2684** [comment]
Closing until there will be a documented API available for achieving this. Thanks
