### ISSUE TITLE
How to get image from imou camera with this repo

### ISSUE THREAD

**Issue by IricsDo** [user2684/imouapi#6]
Sorry If my question is stupid. I have a imou camera in my house, I want to get image from this camera with python code to run my application( some personal application). 
But I don't know how can I do. Is this repo have the API for this task?

Thanks everyone. 
Wish you have a nice day !

**Comment by user2684** [comment]
Sure, after installing the library with `pip install imouapi`, you can interact with it using the CLI with `python -m imouapi.cli`.
Specifically either with the command `get_camera_image `or other low level api calls.
